<?php
    $name = "Saung Hayman Oo";
    echo strlen($name);
    echo "<br>";
    echo str_word_count($name);
echo "<br>";
echo strrev($name);
echo "<br>";
echo str_shuffle($name);
echo "<br>";
echo strpos($name,"Oo");
echo "<br>";
echo substr($name,0,5);
echo "<br>";
echo strtoupper($name);
echo "<br>";
echo strtolower($name);
echo "<br>";
echo ucfirst($name);
echo "<br>";
echo ucwords($name);
echo "<br>";
echo str_replace("Saung","Hsung",$name);
echo "<br>";
print_r(str_split($name));
echo "<br>";
print_r(str_split($name,5));
echo "<br>";
print_r(explode(' ',$name));